---
layout: post
title:  "Python异常"
date:   2017-04-02
excerpt: "本文主要介绍Python语法中异常的相关知识."
project: true
tag:
- Python 
- 异常
comments: true
---
# Python异常
---

 ![1.jpg](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1490719059480&di=a4e59ef124419e527f2c37a528751d3f&imgtype=0&src=http%3A%2F%2Fimage.coolapk.com%2Ffeed%2F2016%2F0516%2F432029_1463394209_0424.jpg.m.jpg){: .image-middle}

当你的程序中出现某些异常的状况的时候，异常就发生了。例如，当你想要读某个文件的时候，而那个文件不存在。或者在程序运行的时候，你不小心把它删除了。上述这些情况可以使用异常来处理。假如你的程序中有一些无效的语句，会怎么样呢？Python会引发并告诉你那里有一个错误，从而处理这样的情况。

## 错误

考虑一个简单的print语句。假如我们把print误拼为Print，注意大写，这样Python会引发一个语法错误。
	>>> Print 'Hello World'	File "<stdin>", line 1	Print 'Hello World'				^	SyntaxError: invalid syntax	>>> print 'Hello World'	Hello World
我们可以观察到有一个SyntaxError被引发，并且检测到的错误位置也被打印了出来。这是这个错误的错误处理器所做的工作。
## try...except

我们尝试读取用户的一段输入。按Ctrl-d，看一下会发生什么。
	>>> s = raw_input('Enter something --> ')	Enter something --> Traceback (most recent call last):	File "<stdin>", line 1, in ?	EOFErrorPython引发了一个称为EOFError的错误，这个错误基本上意味着它发现一个不期望的文件尾（由Ctrl-d表示）
接下来，我们将学习如何处理这样的错误。

	#!/usr/bin/python	# Filename: try_except.py	import sys	try:		s = raw_input('Enter something --> ')	except EOFError:		print '\nWhy did you do an EOF on me?'		sys.exit() # exit the program	except:		print '\nSome error/exception occurred.'		# here, we are not exiting the program	print 'Done'	
	
输出

	$ python try_except.py	Enter something -->	Why did you do an EOF on me?	$ python try_except.py	Enter something --> Python is exceptional!	Done

## 引发异常

你可以使用raise语句引发异常。你还得指明错误/异常的名称和伴随异常 触发的异常对象。你可以引发的错误或异常应该分别是一个Error或Exception类的直接或间接导出类。

	#!/usr/bin/python	# Filename: raising.py	class ShortInputException(Exception):		'''A user-defined exception class.'''		def __init__(self, length, atleast):			Exception.__init__(self)			self.length = length			self.atleast = atleast		try:			s = raw_input('Enter something --> ')			if len(s) < 3:				raise ShortInputException(len(s), 3)			# Other work can continue as usual here		except EOFError:			print '\nWhy did you do an EOF on me?'		except ShortInputException, x:			print 'ShortInputException: The input was of length %d, \				was expecting at least %d' % (x.length, x.atleast)		else:			print 'No exception was raised.'
			
输出

	$ python raising.py	Enter something -->	Why did you do an EOF on me?	$ python raising.py	Enter something --> ab	ShortInputException: The input was of length 2, was expecting at least 3	$ python raising.py	Enter something --> abc	No exception was raised.
	
## try..finally

假如你在读一个文件的时候，希望在无论异常发生与否的情况下都关闭文件，该怎么做呢？这可以使用finally块来完成。注意，在一个try块下，你可以同时使用except从句和finally块。如果你要同时使用它们的话，需要把一个嵌入另外一个。

	#!/usr/bin/python	# Filename: finally.py	import time	try:		f = file('poem.txt')		while True: # our usual file-reading idiom			line = f.readline()			if len(line) == 0:				break			time.sleep(2)			print line,	finally:		f.close()		print 'Cleaning up...closed the file'
		
输出

	$ python finally.py	Programming is fun	When the work is done	Cleaning up...closed the file	Traceback (most recent call last):	File "finally.py", line 12, in ?		time.sleep(2)	KeyboardInterrupt